---
name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    environment: main
    permissions: {}
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: token
        with:
          app_id: ${{ vars.DEMO_SERVER_APP_ID }}
          private_key: ${{ secrets.DEMO_SERVER_PRIVATE_KEY }}
          repositories: >-
            ["demo-client"]
          permissions: >-
            {
              "pull_requests": "write"
            }
